# Generated by Django 4.2.14 on 2025-05-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_orderitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
