# Generated by Django 4.2.20 on 2025-05-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_filial_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Rad etilgan'), (2, 'Kutilmoqda'), (3, 'Tasdiqlangan'), (4, 'Bajarildi ')], default=2, max_length=255),
        ),
    ]
