# Generated by Django 5.2 on 2025-05-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_order_phone_number1_alter_order_phone_number2'),
        ('Product', '0007_alter_order_status'),
    ]

    operations = [
    ]
