# Generated by Django 4.2.20 on 2025-05-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_order_phone_number1_alter_order_phone_number2'),
        ('Product', '0007_alter_order_status'),
    ]

    operations = [
    ]
