# Generated by Django 4.2.20 on 2025-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_merge_20250512_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Rad etilgan'), (2, 'Kutilmoqda'), (3, 'Tasdiqlangan'), (4, 'Topshirildi ')], default=2),
        ),
    ]
