<<<<<<< HEAD
# Generated by Django 4.2.20 on 2025-05-12 10:28
=======
# Generated by Django 5.2 on 2025-05-08 12:12
>>>>>>> 3023fd1e96b867611c86dc283aa437ba00d9d5e6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('Product', '0008_merge_20250512_1526'),
=======
        ('Product', '0008_merge_20250508_1608'),
>>>>>>> 3023fd1e96b867611c86dc283aa437ba00d9d5e6
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
<<<<<<< HEAD
            field=models.IntegerField(choices=[(1, 'Rad etilgan'), (2, 'Kutilmoqda'), (3, 'Tasdiqlangan'), (4, 'Topshirildi ')], default=2),
=======
            field=models.CharField(choices=[('1', 'Rad etilgan'), ('2', 'Kutilmoqda'), ('3', 'Tasdiqlangan'), ('4', 'Topshirildi ')], default=2, max_length=255),
>>>>>>> 3023fd1e96b867611c86dc283aa437ba00d9d5e6
        ),
    ]
