# Generated by Django 5.2 on 2025-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_merge_20250508_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Rad etilgan'), ('2', 'Kutilmoqda'), ('3', 'Tasdiqlangan'), ('4', 'Topshirildi ')], default=2, max_length=255),
        ),
    ]
