# Generated by Django 4.2.20 on 2025-05-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_merge_20250508_1608'),
        ('Product', '0008_merge_20250512_1526'),
    ]

    operations = [
    ]
