# Generated by Django 4.2.20 on 2025-05-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog'),
        ('main', '0002_eskiztoken'),
    ]

    operations = [
    ]
